#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                     - Verkefni 3 - 1. hluti -                                      *|
|*                                                                                                    *|
|*  This program uses the left joystick to move the robot forward and backward and the right joystick *|
|*  to turn.                                                                                          *|
|*                                                                                                    *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{
	short rightJoyXValue;
	short leftJoyYValue;
  while (true) {
  	rightJoyXValue = vexRT[Ch1];  // Right joystick X axis
  	leftJoyYValue = vexRT[Ch3];   // Left joystick Y axis
  	// Turning sideways
    if (rightJoyXValue != 0) {
    	motor[leftMotor]  =  rightJoyXValue;
    	motor[rightMotor] = -rightJoyXValue;
    }
    // Going forward
    else {
    	motor[leftMotor]  = leftJoyYValue;
    	motor[rightMotor] = leftJoyYValue;
    }
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
